### ISSUE TITLE
UID and GID choice limitation

### ISSUE THREAD

**Issue by yar** [jdeathe/centos-ssh#472]
Why is it required for UID and GID specified via SSH_USER_ID to be 500 or higher?

In my case, this centos-ssh image works in pair with the official wordpress image which saves the source code as UID 33, GID 33.  In order for the ssh user to be able to write to the same files, it would be convenient to set SSH_USER_ID to "33:33", but I cannot.

**Comment by jdeathe** [comment]
@yar Please supply a test case for me and I will consider this change. The limit is there because the non system accounts on CentOS[-6] start from 500. System accounts count down from 499.

**Comment by yar** [comment]
Would this test (1bd7f48dc213f067ef41ef1bf77c4a1dc3b68853) serve the purpose?

**Comment by jdeathe** [comment]
@yar I mean I want to see the actual docker run commands you are currently using. It might be something that can be worked around by specifying the --user or setting the additional groups.

**Comment by yar** [comment]
Here is my example of the actual usage:

```yaml
# docker-compose.yml

wordpress:
  image: wordpress:4.7-php7.0-apache
  links:
    - wordpress_db:mysql
  ports:
    - 127.0.0.1:8980:80
  volumes:
    - /foo/bar/wordpress/web/wp_html:/var/www/html
    - /foo/bar/wordpress/php.ini:/usr/local/etc/php/conf.d/larger_uploads.ini
  restart: always
wordpress_db:
  image: mariadb
  volumes:
    - /foo/bar/wordpress/db/_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: redacted
  ports:
    - 127.0.0.1:8982:3306
  restart: always
ssh:
  image: jdeathe/centos-ssh:centos-7
  volumes:
    - /foo/bar/wordpress/web/wp_html/blog:/www/blog
  ports:
    - "8822:22"
  environment:
    SSH_USER: foobar
    SSH_USER_ID: "33:33"
    SSH_USER_PASSWORD_HASHED: "true"
    SSH_USER_PASSWORD: redacted
    SSH_AUTHORIZED_KEYS: redacted
  restart: always
````
